// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  fleetScope: __t.u32().name("fleet_scope"),
  address: __t.string(),
  bbl: __t.option(__t.string()),
  sqft: __t.u32(),
  isAffordable: __t.bool().name("is_affordable"),
  annualEmissionsTco2E: __t.option(__t.f64()).name("annual_emissions_tco_2_e"),
  usesJson: __t.option(__t.string()).name("uses_json"),
  ll97Covered: __t.option(__t.bool()).name("ll_97_covered"),
  provenanceJson: __t.option(__t.string()).name("provenance_json"),
  numFloors: __t.option(__t.u32()).name("num_floors"),
  unitsResidential: __t.option(__t.u32()).name("units_residential"),
  communityDistrict: __t.option(__t.u32()).name("community_district"),
  energyStarScore: __t.option(__t.u32()).name("energy_star_score"),
  compliancePlanJson: __t.option(__t.string()).name("compliance_plan_json"),
  createdAt: __t.timestamp().name("created_at"),
});
