// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Approval = __t.object("Approval", {
  id: __t.u64(),
  owner: __t.identity(),
  fleetScope: __t.u32(),
  taskId: __t.u64(),
  approvedBy: __t.identity(),
  verdict: __t.string(),
  note: __t.string(),
  at: __t.timestamp(),
});
export type Approval = __Infer<typeof Approval>;

export const BinderEvent = __t.object("BinderEvent", {
  id: __t.u64(),
  owner: __t.identity(),
  fleetScope: __t.u32(),
  buildingId: __t.u64(),
  obligationId: __t.option(__t.u64()),
  lawId: __t.string(),
  kind: __t.string(),
  summary: __t.string(),
  at: __t.timestamp(),
});
export type BinderEvent = __Infer<typeof BinderEvent>;

export const Building = __t.object("Building", {
  id: __t.u64(),
  owner: __t.identity(),
  fleetScope: __t.u32(),
  address: __t.string(),
  bbl: __t.option(__t.string()),
  bin: __t.option(__t.string()),
  sqft: __t.u32(),
  isAffordable: __t.bool(),
  annualEmissionsTco2E: __t.option(__t.f64()),
  usesJson: __t.option(__t.string()),
  ll97Covered: __t.option(__t.bool()),
  provenanceJson: __t.option(__t.string()),
  numFloors: __t.option(__t.u32()),
  unitsResidential: __t.option(__t.u32()),
  communityDistrict: __t.option(__t.u32()),
  energyStarScore: __t.option(__t.u32()),
  compliancePlanJson: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type Building = __Infer<typeof Building>;

export const Event = __t.object("Event", {
  id: __t.u64(),
  owner: __t.identity(),
  kind: __t.string(),
  taskId: __t.option(__t.u64()),
  workerId: __t.option(__t.u64()),
  payload: __t.string(),
  at: __t.timestamp(),
});
export type Event = __Infer<typeof Event>;

export const Evidence = __t.object("Evidence", {
  id: __t.u64(),
  owner: __t.identity(),
  fleetScope: __t.u32(),
  obligationId: __t.u64(),
  buildingId: __t.u64(),
  lawId: __t.string(),
  fileName: __t.string(),
  fileType: __t.string(),
  fileUrlOrKey: __t.string(),
  uploadedBy: __t.string(),
  uploadedAt: __t.timestamp(),
  documentDate: __t.option(__t.timestamp()),
  expirationDate: __t.option(__t.timestamp()),
  issuer: __t.string(),
  vendorId: __t.option(__t.u64()),
  filingReferenceNumber: __t.string(),
  verificationStatus: __t.string(),
  notes: __t.string(),
});
export type Evidence = __Infer<typeof Evidence>;

export const Obligation = __t.object("Obligation", {
  id: __t.u64(),
  owner: __t.identity(),
  fleetScope: __t.u32(),
  buildingId: __t.u64(),
  lawId: __t.string(),
  title: __t.string(),
  status: __t.string(),
  dueDate: __t.option(__t.timestamp()),
  responsibleParty: __t.string(),
  vendorId: __t.option(__t.u64()),
  filingReferenceNumber: __t.string(),
  notes: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  completedAt: __t.option(__t.timestamp()),
});
export type Obligation = __Infer<typeof Obligation>;

export const ReaperTick = __t.object("ReaperTick", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type ReaperTick = __Infer<typeof ReaperTick>;

export const Settings = __t.object("Settings", {
  owner: __t.identity(),
  reviewMode: __t.string(),
});
export type Settings = __Infer<typeof Settings>;

export const Submission = __t.object("Submission", {
  id: __t.u64(),
  owner: __t.identity(),
  fleetScope: __t.u32(),
  taskId: __t.u64(),
  workerId: __t.u64(),
  body: __t.string(),
  payloadJson: __t.option(__t.string()),
  submittedAt: __t.timestamp(),
});
export type Submission = __Infer<typeof Submission>;

export const Task = __t.object("Task", {
  id: __t.u64(),
  owner: __t.identity(),
  fleetScope: __t.u32(),
  buildingId: __t.u64(),
  lawId: __t.string(),
  kind: __t.string(),
  title: __t.string(),
  status: __t.string(),
  deadline: __t.timestamp(),
  slaBreached: __t.bool(),
  fineEstimateUsd: __t.option(__t.u32()),
  claimedBy: __t.option(__t.u64()),
  intakeAddress: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type Task = __Infer<typeof Task>;

export const Vendor = __t.object("Vendor", {
  id: __t.u64(),
  owner: __t.identity(),
  fleetScope: __t.u32(),
  name: __t.string(),
  company: __t.string(),
  roleType: __t.string(),
  email: __t.string(),
  phone: __t.string(),
  licenseNumber: __t.string(),
  licenseType: __t.string(),
  notes: __t.string(),
  createdAt: __t.timestamp(),
});
export type Vendor = __Infer<typeof Vendor>;

export const Worker = __t.object("Worker", {
  id: __t.u64(),
  identity: __t.identity(),
  fleetScope: __t.u32(),
  name: __t.string(),
  status: __t.string(),
  lastHeartbeat: __t.timestamp(),
  currentTaskId: __t.option(__t.u64()),
});
export type Worker = __Infer<typeof Worker>;

