// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Approval = __t.object("Approval", {
  id: __t.u64(),
  taskId: __t.u64(),
  approvedBy: __t.identity(),
  verdict: __t.string(),
  note: __t.string(),
  at: __t.timestamp(),
});
export type Approval = __Infer<typeof Approval>;

export const Building = __t.object("Building", {
  id: __t.u64(),
  address: __t.string(),
  bbl: __t.option(__t.string()),
  sqft: __t.u32(),
  isAffordable: __t.bool(),
  annualEmissionsTco2E: __t.option(__t.f64()),
  usesJson: __t.option(__t.string()),
  ll97Covered: __t.option(__t.bool()),
  provenanceJson: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type Building = __Infer<typeof Building>;

export const Event = __t.object("Event", {
  id: __t.u64(),
  kind: __t.string(),
  taskId: __t.option(__t.u64()),
  workerId: __t.option(__t.u64()),
  payload: __t.string(),
  at: __t.timestamp(),
});
export type Event = __Infer<typeof Event>;

export const ReaperTick = __t.object("ReaperTick", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type ReaperTick = __Infer<typeof ReaperTick>;

export const Submission = __t.object("Submission", {
  id: __t.u64(),
  taskId: __t.u64(),
  workerId: __t.u64(),
  body: __t.string(),
  submittedAt: __t.timestamp(),
});
export type Submission = __Infer<typeof Submission>;

export const Task = __t.object("Task", {
  id: __t.u64(),
  buildingId: __t.u64(),
  lawId: __t.string(),
  kind: __t.string(),
  title: __t.string(),
  status: __t.string(),
  deadline: __t.timestamp(),
  slaBreached: __t.bool(),
  fineEstimateUsd: __t.option(__t.u32()),
  claimedBy: __t.option(__t.u64()),
  createdAt: __t.timestamp(),
});
export type Task = __Infer<typeof Task>;

export const Worker = __t.object("Worker", {
  id: __t.u64(),
  identity: __t.identity(),
  name: __t.string(),
  status: __t.string(),
  lastHeartbeat: __t.timestamp(),
  currentTaskId: __t.option(__t.u64()),
});
export type Worker = __Infer<typeof Worker>;

