// The row shapes the dashboard consumes. Formerly generated by SpacetimeDB into
// module_bindings/types; now hand-defined here so the app has no dependency on
// SpacetimeDB. shape.ts maps Supabase rows into exactly these shapes (bigint
// ids, a Timestamp-like { toDate() }, camelCase, `undefined` for absent
// options), so component bodies are unchanged.

// Minimal stand-in for SpacetimeDB's Timestamp — components only call .toDate()
// (sometimes chained to .getTime()/.toISOString()/.toLocaleDateString()).
export interface StdbTimestamp {
  toDate(): Date;
}

export interface Task {
  id: bigint;
  owner: string;
  fleetScope: number;
  buildingId: bigint;
  lawId: string;
  kind: string;
  title: string;
  status: string;
  deadline: StdbTimestamp;
  slaBreached: boolean;
  fineEstimateUsd: number | undefined;
  claimedBy: bigint | undefined;
  intakeAddress: string | undefined;
  createdAt: StdbTimestamp;
}

export interface Building {
  id: bigint;
  owner: string;
  fleetScope: number;
  address: string;
  bbl: string | undefined;
  bin: string | undefined;
  sqft: number;
  isAffordable: boolean;
  annualEmissionsTco2E: number | undefined;
  usesJson: string | undefined;
  ll97Covered: boolean | undefined;
  provenanceJson: string | undefined;
  numFloors: number | undefined;
  unitsResidential: number | undefined;
  communityDistrict: number | undefined;
  energyStarScore: number | undefined;
  compliancePlanJson: string | undefined;
  systemsJson: string | undefined;
  createdAt: StdbTimestamp;
}

export interface Submission {
  id: bigint;
  owner: string;
  fleetScope: number;
  taskId: bigint;
  workerId: bigint;
  body: string;
  payloadJson: string | undefined;
  submittedAt: StdbTimestamp;
}

export interface Settings {
  owner: string;
  reviewMode: string;
}

export interface Event {
  id: bigint;
  owner: string;
  kind: string;
  taskId: bigint | undefined;
  workerId: bigint | undefined;
  payload: string;
  at: StdbTimestamp;
}

export interface Vendor {
  id: bigint;
  owner: string;
  fleetScope: number;
  name: string;
  company: string;
  roleType: string;
  email: string;
  phone: string;
  licenseNumber: string;
  licenseType: string;
  notes: string;
  createdAt: StdbTimestamp;
}

export interface Obligation {
  id: bigint;
  owner: string;
  fleetScope: number;
  buildingId: bigint;
  lawId: string;
  title: string;
  status: string;
  dueDate: StdbTimestamp | undefined;
  responsibleParty: string;
  vendorId: bigint | undefined;
  filingReferenceNumber: string;
  notes: string;
  createdAt: StdbTimestamp;
  updatedAt: StdbTimestamp;
  completedAt: StdbTimestamp | undefined;
}

export interface Evidence {
  id: bigint;
  owner: string;
  fleetScope: number;
  obligationId: bigint;
  buildingId: bigint;
  lawId: string;
  fileName: string;
  fileType: string;
  fileUrlOrKey: string;
  uploadedBy: string;
  uploadedAt: StdbTimestamp;
  documentDate: StdbTimestamp | undefined;
  expirationDate: StdbTimestamp | undefined;
  issuer: string;
  vendorId: bigint | undefined;
  filingReferenceNumber: string;
  verificationStatus: string;
  notes: string;
}

export interface BinderEvent {
  id: bigint;
  owner: string;
  fleetScope: number;
  buildingId: bigint;
  obligationId: bigint | undefined;
  lawId: string;
  kind: string;
  summary: string;
  at: StdbTimestamp;
}

export interface Worker {
  id: bigint;
  identity: string | undefined;
  fleetScope: number;
  name: string;
  status: string;
  lastHeartbeat: StdbTimestamp;
  currentTaskId: bigint | undefined;
}

// One uploaded document in a building's standardized library. Fineprint keeps the
// file plus a consistent set of cover-sheet fields; it never re-keys the document.
export interface BuildingDocument {
  id: bigint;
  owner: string;
  buildingId: bigint;
  storagePath: string;
  fileName: string;
  docType: string;
  documentDate: string | null;
  referenceNumber: string;
  note: string;
  uploadedAt: StdbTimestamp;
}
