// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddBuildingReducer from "../add_building_reducer";
import ApproveReducer from "../approve_reducer";
import ClaimTaskReducer from "../claim_task_reducer";
import HeartbeatReducer from "../heartbeat_reducer";
import KillWorkerReducer from "../kill_worker_reducer";
import RegisterWorkerReducer from "../register_worker_reducer";
import RejectReducer from "../reject_reducer";
import SubmitWorkReducer from "../submit_work_reducer";

export type AddBuildingParams = __Infer<typeof AddBuildingReducer>;
export type ApproveParams = __Infer<typeof ApproveReducer>;
export type ClaimTaskParams = __Infer<typeof ClaimTaskReducer>;
export type HeartbeatParams = __Infer<typeof HeartbeatReducer>;
export type KillWorkerParams = __Infer<typeof KillWorkerReducer>;
export type RegisterWorkerParams = __Infer<typeof RegisterWorkerReducer>;
export type RejectParams = __Infer<typeof RejectReducer>;
export type SubmitWorkParams = __Infer<typeof SubmitWorkReducer>;

