// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddBinderNoteReducer from "../add_binder_note_reducer";
import AddBuildingReducer from "../add_building_reducer";
import AddEvidenceReducer from "../add_evidence_reducer";
import AddVendorReducer from "../add_vendor_reducer";
import ApproveReducer from "../approve_reducer";
import AssignVendorReducer from "../assign_vendor_reducer";
import ClaimTaskReducer from "../claim_task_reducer";
import FailIntakeReducer from "../fail_intake_reducer";
import HeartbeatReducer from "../heartbeat_reducer";
import IngestBuildingReducer from "../ingest_building_reducer";
import KillWorkerReducer from "../kill_worker_reducer";
import MarkDoneReducer from "../mark_done_reducer";
import PruneDeadWorkersReducer from "../prune_dead_workers_reducer";
import RegisterWorkerReducer from "../register_worker_reducer";
import RejectReducer from "../reject_reducer";
import RequestBuildingReducer from "../request_building_reducer";
import SeedObligationsReducer from "../seed_obligations_reducer";
import SetEvidenceVerificationReducer from "../set_evidence_verification_reducer";
import SetObligationStatusReducer from "../set_obligation_status_reducer";
import SetReviewModeReducer from "../set_review_mode_reducer";
import SubmitWorkReducer from "../submit_work_reducer";

export type AddBinderNoteParams = __Infer<typeof AddBinderNoteReducer>;
export type AddBuildingParams = __Infer<typeof AddBuildingReducer>;
export type AddEvidenceParams = __Infer<typeof AddEvidenceReducer>;
export type AddVendorParams = __Infer<typeof AddVendorReducer>;
export type ApproveParams = __Infer<typeof ApproveReducer>;
export type AssignVendorParams = __Infer<typeof AssignVendorReducer>;
export type ClaimTaskParams = __Infer<typeof ClaimTaskReducer>;
export type FailIntakeParams = __Infer<typeof FailIntakeReducer>;
export type HeartbeatParams = __Infer<typeof HeartbeatReducer>;
export type IngestBuildingParams = __Infer<typeof IngestBuildingReducer>;
export type KillWorkerParams = __Infer<typeof KillWorkerReducer>;
export type MarkDoneParams = __Infer<typeof MarkDoneReducer>;
export type PruneDeadWorkersParams = __Infer<typeof PruneDeadWorkersReducer>;
export type RegisterWorkerParams = __Infer<typeof RegisterWorkerReducer>;
export type RejectParams = __Infer<typeof RejectReducer>;
export type RequestBuildingParams = __Infer<typeof RequestBuildingReducer>;
export type SeedObligationsParams = __Infer<typeof SeedObligationsReducer>;
export type SetEvidenceVerificationParams = __Infer<typeof SetEvidenceVerificationReducer>;
export type SetObligationStatusParams = __Infer<typeof SetObligationStatusReducer>;
export type SetReviewModeParams = __Infer<typeof SetReviewModeReducer>;
export type SubmitWorkParams = __Infer<typeof SubmitWorkReducer>;

