// Phase 2 entry point: get the REMDB measure data, normalize it into the shared
// schema, and write both the normalized data file and a debug report.
//
//   npm run fetch:remdb
//
// REMDB has no JSON API — it ships as a public .xlsx, so no OpenEI key is needed.
// The script downloads the file once (cached in data/remdb/), reads the
// "Machine Read" sheet, and hands the rows to the pure normalizer. It never
// invents measures: a row with no cost coefficients yields null costs, not zeros.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import * as XLSX from "xlsx";

import {
  normalizeRemdbSheet,
  REMDB_SHEET,
  REMDB_XLSX_FILENAME,
  REMDB_XLSX_URL,
  type RemdbParseReport,
} from "../src/remdb.ts";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const xlsxPath = join(repoRoot, "data", "remdb", REMDB_XLSX_FILENAME);
const measuresPath = join(repoRoot, "data", "remdb", "remdb_measures.json");
const reportPath = join(repoRoot, "data", "normalized", "remdb_fetch_report.md");

function list(items: string[]): string {
  return items.length > 0 ? items.map(item => `- ${item}`).join("\n") : "- (none)";
}

function renderReport(report: RemdbParseReport): string {
  return `# REMDB fetch report

_Generated by \`npm run fetch:remdb\`._

## Source

- API key required: **no** (REMDB has no API; it is a public .xlsx download)
- Source file: \`${report.sourceFile}\`
- Source URL: ${report.sourceUrl}
- Sheet read: \`${report.sheet}\`

## Measures

- Data rows in sheet: **${report.rawRowCount}**
- Normalized measures written: **${report.normalizedMeasureCount}**

## Field mapping

Columns seen in the sheet:

${list(report.columnsSeen)}

Schema fields successfully mapped (non-null for at least one measure):

${list(report.mappedFields)}

Schema fields missing (null across every measure):

${list(report.missingFields)}

## Errors

${list(report.errors)}

## Assumptions

${list(report.assumptions)}
`;
}

async function downloadIfMissing(): Promise<void> {
  if (existsSync(xlsxPath)) {
    return;
  }
  console.log(`Downloading REMDB workbook from ${REMDB_XLSX_URL} ...`);
  const response = await fetch(REMDB_XLSX_URL);
  if (!response.ok) {
    throw new Error(
      `REMDB download failed: ${response.status} ${response.statusText} for ${REMDB_XLSX_URL}`,
    );
  }
  const bytes = Buffer.from(await response.arrayBuffer());
  mkdirSync(dirname(xlsxPath), { recursive: true });
  writeFileSync(xlsxPath, bytes);
  console.log(`Saved ${bytes.length} bytes to ${xlsxPath}`);
}

async function main(): Promise<void> {
  await downloadIfMissing();

  const workbook = XLSX.read(readFileSync(xlsxPath), { type: "buffer" });
  const sheet = workbook.Sheets[REMDB_SHEET];
  if (!sheet) {
    throw new Error(
      `REMDB workbook has no "${REMDB_SHEET}" sheet (found: ${workbook.SheetNames.join(", ")})`,
    );
  }
  const rows = XLSX.utils.sheet_to_json<unknown[]>(sheet, { header: 1, blankrows: false });

  const { measures, report } = normalizeRemdbSheet(rows);

  mkdirSync(dirname(measuresPath), { recursive: true });
  mkdirSync(dirname(reportPath), { recursive: true });
  writeFileSync(measuresPath, `${JSON.stringify(measures, null, 2)}\n`);
  writeFileSync(reportPath, renderReport(report));

  console.log(`Wrote ${measures.length} normalized measures to ${measuresPath}`);
  console.log(`Wrote fetch report to ${reportPath}`);

  if (report.normalizedMeasureCount === 0) {
    console.error("\nNo measures were normalized. See the report's Errors section.");
    process.exitCode = 1;
  }
}

main().catch((error: Error) => {
  console.error(`fetch-remdb failed: ${error.message}`);
  process.exitCode = 1;
});
