// Phase 2 entry point: fetch REMDB measures from OpenEI, normalize them into the
// shared schema, and write both the normalized data file and a debug report.
//
//   npm run fetch:remdb
//
// The OpenEI key is read from the environment (OPENEI_API_KEY via .env.local),
// never hardcoded. When the key is absent or the request fails, the script still
// writes an (empty) data file and a report that states exactly what happened —
// it never invents measures to fill the gap.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { loadEnvLocal } from "../src/loadEnv.ts";
import { fetchRemdbMeasures, type RemdbFetchReport } from "../src/remdb.ts";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const measuresPath = join(repoRoot, "data", "remdb", "remdb_measures.json");
const reportPath = join(repoRoot, "data", "normalized", "remdb_fetch_report.md");

function renderReport(report: RemdbFetchReport): string {
  const list = (items: string[]) =>
    items.length > 0 ? items.map(item => `- ${item}`).join("\n") : "- (none)";

  return `# REMDB fetch report

_Generated by \`npm run fetch:remdb\`._

## Key and source

- OPENEI_API_KEY found: **${report.keyFound ? "yes" : "no"}**
- Endpoint attempted: \`${report.endpoint}\`

## Measures

- Raw measures returned: **${report.rawMeasureCount}**
- Normalized measures written: **${report.normalizedMeasureCount}**

## Field mapping

Raw keys seen in the response:

${list(report.rawKeysSeen)}

Schema fields successfully mapped (non-null for at least one measure):

${list(report.mappedFields)}

Schema fields missing (null across every measure):

${list(report.missingFields)}

## Errors

${list(report.errors)}

## Assumptions

${list(report.assumptions)}
`;
}

async function main(): Promise<void> {
  loadEnvLocal();

  const apiKey = process.env.OPENEI_API_KEY;
  const { measures, report } = await fetchRemdbMeasures(apiKey);

  mkdirSync(dirname(measuresPath), { recursive: true });
  mkdirSync(dirname(reportPath), { recursive: true });
  writeFileSync(measuresPath, `${JSON.stringify(measures, null, 2)}\n`);
  writeFileSync(reportPath, renderReport(report));

  console.log(`Wrote ${measures.length} normalized measures to ${measuresPath}`);
  console.log(`Wrote fetch report to ${reportPath}`);

  if (!report.keyFound) {
    console.error(
      "\nOPENEI_API_KEY was not found in the environment (.env.local). " +
        "Add it and re-run; no measures were fetched and none were invented.",
    );
    process.exitCode = 1;
    return;
  }
  if (report.normalizedMeasureCount === 0) {
    console.error("\nNo measures were normalized. See the report's Errors section.");
    process.exitCode = 1;
  }
}

main().catch((error: Error) => {
  console.error(`fetch-remdb failed: ${error.message}`);
  process.exitCode = 1;
});
