// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  obligationId: __t.u64(),
  fileName: __t.string(),
  fileType: __t.string(),
  fileUrlOrKey: __t.string(),
  uploadedBy: __t.string(),
  issuer: __t.string(),
  filingReferenceNumber: __t.string(),
  notes: __t.string(),
};
