// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  fleetScope: __t.u32().name("fleet_scope"),
  buildingId: __t.u64().name("building_id"),
  obligationId: __t.option(__t.u64()).name("obligation_id"),
  lawId: __t.string().name("law_id"),
  kind: __t.string(),
  summary: __t.string(),
  at: __t.timestamp(),
});
