// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  fleetScope: __t.u32().name("fleet_scope"),
  obligationId: __t.u64().name("obligation_id"),
  buildingId: __t.u64().name("building_id"),
  lawId: __t.string().name("law_id"),
  fileName: __t.string().name("file_name"),
  fileType: __t.string().name("file_type"),
  fileUrlOrKey: __t.string().name("file_url_or_key"),
  uploadedBy: __t.string().name("uploaded_by"),
  uploadedAt: __t.timestamp().name("uploaded_at"),
  documentDate: __t.option(__t.timestamp()).name("document_date"),
  expirationDate: __t.option(__t.timestamp()).name("expiration_date"),
  issuer: __t.string(),
  vendorId: __t.option(__t.u64()).name("vendor_id"),
  filingReferenceNumber: __t.string().name("filing_reference_number"),
  verificationStatus: __t.string().name("verification_status"),
  notes: __t.string(),
});
