// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  address: __t.string(),
  bbl: __t.string(),
  sqft: __t.u32(),
  isArticle321: __t.bool(),
  annualEmissionsTco2E: __t.option(__t.f64()),
  usesJson: __t.string(),
  coveredLawIdsJson: __t.string(),
  provenanceJson: __t.string(),
};
