// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  fleetScope: __t.u32().name("fleet_scope"),
  buildingId: __t.u64().name("building_id"),
  lawId: __t.string().name("law_id"),
  title: __t.string(),
  status: __t.string(),
  dueDate: __t.option(__t.timestamp()).name("due_date"),
  responsibleParty: __t.string().name("responsible_party"),
  vendorId: __t.option(__t.u64()).name("vendor_id"),
  filingReferenceNumber: __t.string().name("filing_reference_number"),
  notes: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  completedAt: __t.option(__t.timestamp()).name("completed_at"),
});
