// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  buildingId: __t.u64().name("building_id"),
  lawId: __t.string().name("law_id"),
  kind: __t.string(),
  title: __t.string(),
  status: __t.string(),
  deadline: __t.timestamp(),
  slaBreached: __t.bool().name("sla_breached"),
  fineEstimateUsd: __t.option(__t.u32()).name("fine_estimate_usd"),
  claimedBy: __t.option(__t.u64()).name("claimed_by"),
  intakeAddress: __t.option(__t.string()).name("intake_address"),
  createdAt: __t.timestamp().name("created_at"),
});
