// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  fleetScope: __t.u32().name("fleet_scope"),
  name: __t.string(),
  company: __t.string(),
  roleType: __t.string().name("role_type"),
  email: __t.string(),
  phone: __t.string(),
  licenseNumber: __t.string().name("license_number"),
  licenseType: __t.string().name("license_type"),
  notes: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
