// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  identity: __t.identity(),
  fleetScope: __t.u32().name("fleet_scope"),
  name: __t.string(),
  status: __t.string(),
  lastHeartbeat: __t.timestamp().name("last_heartbeat"),
  currentTaskId: __t.option(__t.u64()).name("current_task_id"),
});
