// Prebakes the demo portfolio. Runs the real intake pipeline (GeoSearch ->
// LL84 -> covered list -> engine) for a curated set of marquee NYC buildings
// and writes the resolved ingest_building arguments to a committed fixture.
//
// The dashboard's "Load demo portfolio" button replays these args through the
// ingest_building reducer under the signed-in user's identity, so the demo is
// the same data path the agent workers use — real engine numbers, real
// obligations — with no live API calls or AI at view time.
//
// Run once, on a machine with network access, after any law/engine change:
//   npx tsx scripts/build-demo-fixtures.ts
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

import { prepareIntake, type IntakeResult } from "../data/src/intake.ts";

// Curated for variety: an over-cap office, a supertall, a downtown tower, an
// outer-borough residential building, and a civic landmark. The first three
// are the addresses the homepage advertises, so its "Try:" chips land on a
// building that actually exists in the seeded portfolio.
const DEMO_ADDRESSES = [
  "1 Wall Street, Manhattan",
  "20 Exchange Place, Manhattan",
  "1870 Pelham Parkway South, Bronx",
  "350 5th Avenue, Manhattan",
  "111 West 57th Street, Manhattan",
  "1 Centre Street, Manhattan",
];

type IngestArgs = IntakeResult["ingestArgs"];

const resolved: IngestArgs[] = [];

for (const address of DEMO_ADDRESSES) {
  process.stdout.write(`Resolving "${address}"… `);
  try {
    const { ingestArgs, summary } = await prepareIntake(address);
    resolved.push(ingestArgs);
    const fine =
      ingestArgs.ll97AnnualFineUsd === undefined
        ? "no LL97 fine"
        : `$${ingestArgs.ll97AnnualFineUsd.toLocaleString("en-US")}/yr`;
    console.log(
      `ok — BBL ${ingestArgs.bbl}, ${ingestArgs.sqft.toLocaleString("en-US")} sqft, ${fine}`,
    );
    void summary;
  } catch (error) {
    console.log(`skipped (${(error as Error).message})`);
  }
}

if (resolved.length === 0) {
  console.error("\nNo addresses resolved — leaving the fixture untouched.");
  process.exit(1);
}

const outputPath = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../client/src/lib/demo-portfolio.ts",
);

const banner =
  "// Generated by scripts/build-demo-fixtures.ts — do not hand-edit.\n" +
  "// Prebaked ingest_building arguments for the demo portfolio, captured from\n" +
  "// the real intake pipeline. Regenerate after any law or engine change.\n";

const body =
  banner +
  "\nexport interface DemoIngestArgs {\n" +
  "  address: string;\n" +
  "  bbl: string;\n" +
  "  sqft: number;\n" +
  "  isArticle321: boolean;\n" +
  "  annualEmissionsTco2E: number | undefined;\n" +
  "  usesJson: string;\n" +
  "  coveredLawIdsJson: string;\n" +
  "  provenanceJson: string;\n" +
  "  ll97AnnualFineUsd: number | undefined;\n" +
  "  compliancePlanJson: string;\n" +
  "}\n\n" +
  `export const DEMO_PORTFOLIO: DemoIngestArgs[] = ${JSON.stringify(resolved, null, 2)};\n`;

await writeFile(outputPath, body, "utf8");
console.log(`\nWrote ${resolved.length} buildings to ${outputPath}`);
process.exit(0);
